# Default values for lsf master.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

master:
  cpu: 1000m
  memory: 2048Mi
  master: icp-worker1
  pvc: symphony
  image:
    repository: master.cfc:8500/default/spectrum-symphony
    tag: 7.2

slave:
  cpu: 1000m
  memory: 2048Mi
  minReplicas: 1
  maxReplicas: 1
  maxReplicasForAs: 1 
  targetCPUUtilizationPercentage: 50
  pvc: symphony
  image:
    repository: master.cfc:8500/default/spectrum-symphony
    tag: 7.2

license:
  key1: "enter license key"
  key2: "enter license key"
