# Default values for lsf master.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

cluster:
  master: icp-worker1
  pvc: symphony
  image:
    repository: master.cfc:8500/default/spectrum-symphony
    tag: 7.2

master:
  cpu: 1000m
  memory: 4096Mb

slave:
  cpu: 1000m
  memory: 2048Mb
  minReplicas: 1
  maxReplicas: 1
  maxReplicasForAs: 1 
  targetCPUUtilizationPercentage: 50

license:
  key1: "enter license key"
  key2: "enter license key"
